
// autogenerated by brownie
// do not modify the existing settings
module.exports = {
    networks: {
        hardhat: {
           forking: {
               url: "https://rpc.ankr.com/fantom",
               blockNumber: 40862836
               
           },
           chainId: 250
       }
    }
}